name = "lotto-studio"
compatibility_date = "2026-07-12"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "lotto-studio-db"
database_id = "488d8cef-3b0b-4564-8a92-a4a27cdaeb66"
